name: Build- PR Check
# Always build on push -- target env == ''; never rebuild if an env is given, as that will fail:
# tag (git sha) already exists.
run-name: >-
  [Build Without Deploy -
  ${{ ( github.event_name == 'release' && github.event.release.tag_name)
      || (github.event.head_commit.message != '' && github.event.head_commit.message)
      || github.sha }}]

on:
  push:
    branches-ignore:
      - hotfix/*    # Handled by hotfix workflow
      - hotfix-*    # Handled by hotfix workflow
      - main        # Handled by standard workflow
      - master      # Handled by standard workflow
  pull_request:
    types: [opened, reopened]

permissions:
  id-token: write
  contents: read
  pull-requests: read

env: {}
  #BASE_BUILDER_IMAGE: eclipse-base:sdk-8.0-b6
  #BASE_RUNTIME_IMAGE: eclipse-base:default-8.0.15-jammy-chiseled-extra-b4

concurrency:
  group: ${{github.repository}}-${{ github.workflow }}-${{ github.ref }}
  # If the branch (ref) is updated, then stop the prior build-test.
  cancel-in-progress: true

jobs:
  is-pr:
    # We need to know if this commit is part of a PR branch. If so, then exit.
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    outputs:
      is-pr: ${{ steps.is-pr.outputs.is-pr == 'true' }}
    steps:
      - name: Detect PRs with this commit
        id: is-pr
        shell: bash
        run: |
          set -x
          { [ "$GITHUB_EVENT_NAME" = "pull_request" ] ||
            [ "${GITHUB_REF#refs/pull/}" != "$GITHUB_REF" ]; }  && {
              echo 'is-pr=true' >> "$GITHUB_OUTPUT"
              exit 0
            }

          set +x
          pr_hashes="$(
          # "Authorization" based on `permissions:' for the workflow, above \
          { curl -Ls \
              -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Authorization: Bearer ${{ github.token }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls; echo $? > curlret-$$; } |
              tee >(grep '"ref"') |
              tee pulls.json |

              # If there's a line that looks like this in the "get PRs" output, we're good.
              grep '"sha": *"' || true)
              )"
          set -x
          curlret="$(cat curlret-$$)"; rm curlret-$$
          if [ ${curlret:-0} -ne 0 ]; then
            echo "::error ::Unable to get information on pulls for this repository. Curl returned error code $curlret."
            curl --include -Ls \
              -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Authorization: Bearer ${{ github.token }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls 2>&1
            exit $curlret
          fi

          # XXX Can I look for head.ref == GITHUB_REF?

          grep -q '"sha": *"${{ github.sha }}"' <<< "$pr_hashes" &&
            echo 'is-pr=true' >> "$GITHUB_OUTPUT" || {
              echo 'is-pr=false' >> "$GITHUB_OUTPUT"
              echo '::error ::Current git SHA hash (${{ github.sha }}) not found in any returned PRs:'
              echo "::error ::$pr_hashes"
              # Don't exit with error; set the output false.
            }

            echo "JSON:"
            cat pulls.json

  snyk-codescan:
    needs:
     - is-pr
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.is-pr.outputs.is-pr == 'true' }}
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Snyk Codescan
        if: ${{ needs.is-pr.outputs.is-pr == 'true' }}
        uses: ./.github/actions/snyk-codescan
        with:
          SHARED_MODULE_READ_KEY: ${{ secrets.GO_PRIVATE_MODULE_READER_PRIVATE_KEY }}
          vars: ${{ toJson(vars) }} # includes shored read ID
          SNYK_TOKEN: ${{ secrets.LSQ_SNYK_TOKEN }}

  build:
    uses: ./.github/workflows/build-deploy.yaml
    if: ${{ needs.is-pr.outputs.is-pr == 'true' }}
    needs:
      - is-pr   # Without this, every branch push will cause a build.
      #- snyk-codescan  # Let the codescan produce a separate result.
    with:
      environment: dev  # For PR pushes, build for dev.
      gitops-repo: Required-unused
      deploy: no    # Build-check only.
      push: false   # Build-check only.
      vars: ${{ toJson(vars) }}
    secrets:
      GO_PRIVATE_MODULE_READER_PRIVATE_KEY: ${{ secrets.GO_PRIVATE_MODULE_READER_PRIVATE_KEY }}
